services:
  - type: web
    name: fastapi
    runtime: docker
    plan: free
    repo: https://github.com/DanelRisa/2023-backend.git
    region: frankfurt
    branch: main
    envVars:
      - key: MONGO_URL
        sync: false
    buildFilter:
      paths:
      - app/**
